services:
    # nginx

  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    env_file: .env


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./images:/usr/share/nginx/html/images
      - ./static:/usr/share/nginx/html/static
      - ./logs:/var/log/nginx